/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Listing = IDL.Record({
  'status' : IDL.Text,
  'model' : IDL.Text,
  'title' : IDL.Text,
  'screenPassCertified' : IDL.Bool,
  'auctionType' : IDL.Text,
  'listingId' : IDL.Text,
  'storage' : IDL.Nat,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
  'serialNumberHash' : IDL.Text,
  'description' : IDL.Text,
  'isDemo' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'batteryHealth' : IDL.Nat,
  'brand' : IDL.Text,
  'sellerId' : IDL.Text,
  'warranty' : IDL.Nat,
  'basePrice' : IDL.Nat,
  'usbVerified' : IDL.Bool,
  'endsAt' : IDL.Int,
  'condition' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'sellerDealer' : IDL.Null,
  'businessBuyer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userRole' : UserRole,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'businessName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'verificationId' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
});
export const Type = IDL.Variant({
  'allListings' : IDL.Null,
  'liveListings' : IDL.Null,
  'sevenDayListings' : IDL.Null,
});
export const Bid = IDL.Record({
  'listingId' : IDL.Text,
  'createdAt' : IDL.Int,
  'bidId' : IDL.Text,
  'bidderId' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createListing' : IDL.Func([Listing], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDemoListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getFilteredListings' : IDL.Func([Type], [IDL.Vec(Listing)], ['query']),
  'getListing' : IDL.Func([IDL.Text], [Listing], ['query']),
  'getListingBids' : IDL.Func([IDL.Text], [IDL.Vec(Bid)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBid' : IDL.Func([Bid], [], []),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Listing = IDL.Record({
    'status' : IDL.Text,
    'model' : IDL.Text,
    'title' : IDL.Text,
    'screenPassCertified' : IDL.Bool,
    'auctionType' : IDL.Text,
    'listingId' : IDL.Text,
    'storage' : IDL.Nat,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
    'serialNumberHash' : IDL.Text,
    'description' : IDL.Text,
    'isDemo' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'batteryHealth' : IDL.Nat,
    'brand' : IDL.Text,
    'sellerId' : IDL.Text,
    'warranty' : IDL.Nat,
    'basePrice' : IDL.Nat,
    'usbVerified' : IDL.Bool,
    'endsAt' : IDL.Int,
    'condition' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'sellerDealer' : IDL.Null,
    'businessBuyer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userRole' : UserRole,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'businessName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'verificationId' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
  });
  const Type = IDL.Variant({
    'allListings' : IDL.Null,
    'liveListings' : IDL.Null,
    'sevenDayListings' : IDL.Null,
  });
  const Bid = IDL.Record({
    'listingId' : IDL.Text,
    'createdAt' : IDL.Int,
    'bidId' : IDL.Text,
    'bidderId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createListing' : IDL.Func([Listing], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDemoListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getFilteredListings' : IDL.Func([Type], [IDL.Vec(Listing)], ['query']),
    'getListing' : IDL.Func([IDL.Text], [Listing], ['query']),
    'getListingBids' : IDL.Func([IDL.Text], [IDL.Vec(Bid)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBid' : IDL.Func([Bid], [], []),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };