/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bid {
  'listingId' : string,
  'createdAt' : bigint,
  'bidId' : string,
  'bidderId' : string,
  'amount' : bigint,
}
export interface Listing {
  'status' : string,
  'model' : string,
  'title' : string,
  'screenPassCertified' : boolean,
  'auctionType' : string,
  'listingId' : string,
  'storage' : bigint,
  'createdAt' : bigint,
  'color' : string,
  'serialNumberHash' : string,
  'description' : string,
  'isDemo' : boolean,
  'imageUrl' : string,
  'batteryHealth' : bigint,
  'brand' : string,
  'sellerId' : string,
  'warranty' : bigint,
  'basePrice' : bigint,
  'usbVerified' : boolean,
  'endsAt' : bigint,
  'condition' : string,
}
export type Type = { 'allListings' : null } |
  { 'liveListings' : null } |
  { 'sevenDayListings' : null };
export interface UserProfile {
  'userRole' : UserRole,
  'userId' : string,
  'createdAt' : bigint,
  'businessName' : string,
  'mobileNumber' : string,
  'verificationId' : string,
  'aadhaarNumber' : string,
}
export type UserRole = { 'sellerDealer' : null } |
  { 'businessBuyer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createListing' : ActorMethod<[Listing], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDemoListings' : ActorMethod<[], Array<Listing>>,
  'getFilteredListings' : ActorMethod<[Type], Array<Listing>>,
  'getListing' : ActorMethod<[string], Listing>,
  'getListingBids' : ActorMethod<[string], Array<Bid>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBid' : ActorMethod<[Bid], undefined>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];